export default function TermsOfServicePage() {
  return (
    <div className="max-w-2xl mx-auto px-4 py-12">
      <h1 className="text-2xl font-bold mb-1">Terms of Service</h1>
      <p className="text-sm text-muted-foreground mb-8">Last updated: 19 June 2025 &mdash; Version 1.0</p>

      <section className="space-y-6 text-sm leading-relaxed text-foreground">

        <div>
          <h2 className="font-semibold text-base mb-2">1. Who we are</h2>
          <p>I Wanna Cook is operated by Alessandro Ladu, Flat 4, 2A Eversley Street, Liverpool, L8 2TG. Email: <a href="mailto:alessandro.dev.ladu@gmail.com" className="underline">alessandro.dev.ladu@gmail.com</a></p>
        </div>

        <div>
          <h2 className="font-semibold text-base mb-2">2. What the app does</h2>
          <p>I Wanna Cook helps users discover recipes, plan meals, scan fridge ingredients, and build shopping lists. Recipe and nutritional data is sourced from Spoonacular. AI features are powered by Anthropic Claude.</p>
        </div>

        <div>
          <h2 className="font-semibold text-base mb-2">3. Accounts</h2>
          <p>You must provide a valid email address and create a username to use the app. You are responsible for keeping your account credentials secure. You must be at least 13 years old to create an account.</p>
        </div>

        <div>
          <h2 className="font-semibold text-base mb-2">4. Subscription and billing</h2>
          <ul className="list-disc pl-5 space-y-2">
            <li><strong>Free plan:</strong> 10 recipe searches per week, 3 ingredient scans per week.</li>
            <li><strong>14-day free trial:</strong> All new accounts receive full Premium access for 14 days at no charge. No payment card is required.</li>
            <li><strong>Premium plan:</strong> $2.49/month or $19.99/year. Unlimited searches, unlimited scans, all premium features. Billed through Google Play (Android) or Apple App Store (iOS).</li>
            <li><strong>Cancellation:</strong> You may cancel at any time through Google Play or the App Store. Access continues until the end of the billing period. No refunds for partial periods.</li>
            <li><strong>Trial to free:</strong> When your trial expires without subscribing, your account automatically moves to the free plan. No data is deleted.</li>
          </ul>
        </div>

        <div>
          <h2 className="font-semibold text-base mb-2">5. What we are not liable for</h2>
          <ul className="list-disc pl-5 space-y-2">
            <li><strong>Nutritional accuracy:</strong> Nutritional information is approximate and sourced from third parties. Do not rely on this app for medically prescribed dietary management.</li>
            <li><strong>Allergic reactions:</strong> Ingredient and allergen information may be incomplete. We are not liable for any adverse reaction caused by reliance on recipe or ingredient information provided by the app. Always verify ingredients independently if you have food allergies or intolerances.</li>
            <li><strong>Service availability:</strong> We do not guarantee uninterrupted access to the app and are not liable for losses resulting from downtime or service interruption.</li>
            <li><strong>Third-party content:</strong> Recipe content is provided by Spoonacular. AI suggestions are generated by Anthropic Claude. We are not responsible for the accuracy or suitability of third-party content.</li>
          </ul>
        </div>

        <div>
          <h2 className="font-semibold text-base mb-2">6. Acceptable use</h2>
          <p className="mb-2">You agree not to:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>Use the app for any unlawful purpose</li>
            <li>Attempt to reverse-engineer, scrape, or copy the app or its content</li>
            <li>Share your account with others</li>
            <li>Use automated tools to access the app</li>
          </ul>
          <p className="mt-2">We reserve the right to suspend or terminate accounts that violate these terms.</p>
        </div>

        <div>
          <h2 className="font-semibold text-base mb-2">7. Account termination</h2>
          <p>You may delete your account at any time via Profile &rarr; Delete Account. We may terminate your account if you breach these terms. On termination, your data is handled as described in our <a href="/privacy" className="underline">Privacy Policy</a>.</p>
        </div>

        <div>
          <h2 className="font-semibold text-base mb-2">8. Changes to these terms</h2>
          <p>We may update these terms from time to time. We will notify you of material changes by email or in-app notice. Continued use of the app after changes constitutes acceptance.</p>
        </div>

        <div>
          <h2 className="font-semibold text-base mb-2">9. Governing law</h2>
          <p>These terms are governed by the laws of England and Wales. Any disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales.</p>
        </div>

        <div>
          <h2 className="font-semibold text-base mb-2">10. Contact</h2>
          <p>Alessandro Ladu, Flat 4, 2A Eversley Street, Liverpool, L8 2TG.<br />Email: <a href="mailto:alessandro.dev.ladu@gmail.com" className="underline">alessandro.dev.ladu@gmail.com</a></p>
        </div>

      </section>
    </div>
  )
}
